### ISSUE TITLE
背景

### ISSUE THREAD

**Issue by Musa-T** [MiaoMint/MiaoHome#3]
你好，背景发白是设置了透明度吗，在哪里可以修改呢，我想显示背景图片的原貌

**Comment by MiaoMint** [comment]
在这里 https://github.com/MiaoMint/MiaoHome/blob/main/index.html#L22

**Comment by Musa-T** [comment]
> 在这里 https://github.com/MiaoMint/MiaoHome/blob/main/index.html#L22

感谢！！
